- hosts: localhost
  gather_facts: no

  vars:
    nginx_controller_user_email: "admin@admin.com"
    nginx_controller_user_password: "test@123"
    nginx_controller_fqdn: "cts.giri.local"
    nginx_controller_validate_certs: false

  tasks:
    - name: Retrieve the NGINX Controller auth token
      include_role:
        name: nginxinc.nginx_controller_generate_token

    - name: Create a gateway
      include_role:
        name: nginxinc.nginx_controller_gateway
      vars:
        # controller.auth_token: output by previous role in example
        nginx_controller_environmentName: "cars"
        nginx_controller_gateway:
          metadata:
            name: cars
            displayName: "cars"
            description: "Routes cars"
          desiredState:
            ingress:
              uris:
                "https://cars.192.168.1.61.nip.io":
                  {}
              tls:
                certRef:
                  ref: "/services/environments/cars/certs/car-cert"
                protocols:
                  - "TLSv1.3"
                  - "TLSv1.2"
              methods:
                  - "POST"
                  - "GET"
              placement:
                instanceRefs:
                  - ref: "/infrastructure/locations/india-zone-east/instances/debserver"

