---
- hosts: back-end-servers
  remote_user: root
  become: true
  become_method: sudo
  gather_facts: yes

  vars:
    api_key: ""
    nginx_controller_fqdn: ""
    nginx_controller_hostname: ""
    nginx_controller_location: ""

  tasks:

  - name: install minimal support for python2 for Agent install script
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python-minimal
      - libxerces-c3.2

  - name: install the agent
    include_role:
      name: nginxinc.nginx_controller_agent
    vars:
      debug: var=ansible_env.HOME
      nginx_controller_api_key: "{{ api_key }}"

  - name: Nginx reload (custom)
    command: nginx -s reload

    
  - name: Service-check
    command: service controller-agent status
    register: details

  - debug: msg="{{ details.stdout_lines }}"

