---
- hosts: back-end-servers
  roles:
    - role: 'nginxinc.nginx'

  tasks: 
    - name: Service-check 
      command: systemctl status nginx
      register: details

    - debug: msg="{{ details.stdout_lines }}"

