#PRE Tasks
---
- hosts: localhost
  vars:
    absolute_file_path: "/root/.ansible/roles/nginxinc.nginx/defaults/main/main.yml"


  tasks:
  - name: Replace nginx-opensource with nginx-plus 
    replace:
      path: "{{ absolute_file_path }}"
      regexp: 'nginx_type: opensource'
      replace: 'nginx_type: plus'

  - name: Verify file
    command: cat "{{ absolute_file_path }}"
    register: details

  - debug: msg="{{ details.stdout_lines }}"

